# Generated by Django 4.2.16 on 2024-12-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_paquete_codigo_alter_paquete_destinatario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacion',
            old_name='fecha_creacion',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='notificacion',
            old_name='leida',
            new_name='visto',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='mensaje',
            field=models.CharField(max_length=255),
        ),
    ]
